# Generated by Django 3.0.6 on 2020-05-19 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='img_product',
            field=models.ImageField(blank=True, null=True, upload_to='products'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Servicio', 'Servicio'), ('Comida', 'Comida'), ('Accesorio', 'Accesorio'), ('Limpieza', 'Limpieza')], max_length=200, null=True),
        ),
    ]
