# Generated by Django 3.0.6 on 2020-05-19 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200518_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='img_product',
            field=models.ImageField(blank=True, null=True, upload_to='productos/'),
        ),
    ]
