# Generated by Django 3.0.6 on 2020-05-22 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200518_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='img_product',
            field=models.ImageField(blank=True, null=True, upload_to='productos'),
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('age', models.IntegerField()),
                ('type_animal', models.CharField(choices=[('Perro', 'Perro'), ('Gato', 'Gato'), ('Ave', 'Ave'), ('Otro', 'Otro')], default='Perro', max_length=15)),
                ('desc', models.CharField(blank=True, default='', max_length=255)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Customer')),
            ],
        ),
    ]
