# Generated by Django 3.0.6 on 2020-05-22 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200518_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='img_product',
            field=models.ImageField(blank=True, null=True, upload_to='productos'),
        ),
    ]
