# Generated by Django 3.0.6 on 2020-05-26 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200522_1434'),
        ('accounts', '0004_auto_20200521_2023'),
    ]

    operations = [
    ]
