# Generated by Django 3.0.5 on 2020-05-22 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_customer_order_pet_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='owner',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Pet',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
